env:
  es6: true
  node: true
extends:
  - "@ianwremmel/eslint-config-standard"
  - prettier
parserOptions:
  ecmaVersion: 2017
  sourceType: script
plugins:
  - prettier
rules:
  prettier/prettier: error
