environment:
  nodejs_version: "lts"
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
version: '{build}'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test

build_script:
  - npm run build
